name: bigquery-grafana

up:
  - node:
      yarn: true
      version: v10.16.3
  - go:
      modules: true
      version: 1.16

commands:
  go:
    run: make build-go
  node:
    run: make build-node
  build:
    run: make build
  run-built:
    run: make run
  release:
    run: make release
